In [4]:
import pandas as pd
import duckdb

pd.set_option("display.max_columns", None)  # show all cols
pd.set_option("display.max_colwidth", None)  # show full width of showing cols
pd.set_option(
    "display.expand_frame_repr", False
)  # print cols side by side as it's supposed to be


ODIS_DUCKDB_FILE = "odis.duckdb"
PCC_DUCKDB_FILE = "dev.duckdb"

con = duckdb.connect(database=PCC_DUCKDB_FILE, read_only=True)
con.sql(f"ATTACH '{ODIS_DUCKDB_FILE}' AS odis;")

BinderException: Binder Error: Failed to attach database: database with name "odis" already exists

In [ ]:
# informacion de comunas y riesgos
query_catnat = """
SELECT *
  FROM dev.main.catnat_gaspar
  ORDER BY cod_commune ASC;
"""

cat_nat = con.sql(query_catnat)
cat_nat_df = cat_nat.df()

query_odis2 = """SELECT * FROM odis.gold_gold_emploi_demandeur
ORDER BY codgeo ASC;
"""
odis_emploi_demandeur = con.sql(query_odis2).df()
# odis_emploi_demandeur["codgeo"] = odis_emploi_demandeur["codgeo"].str.zfill(5)


query_odis3 = """SELECT * FROM odis.gold_gold_typologies_territoires
ORDER BY codgeo ASC;"""
odis_topology = con.sql(query_odis3).df()

In [ ]:
no_numericos = odis_topology[
    ~odis_topology["codgeo"].astype(str).str.match(r"^\d+(\.\d+)?$")
]
for v in no_numericos["codgeo"]:
    print(v)

2A001
2A004
2A006
2A008
2A011
2A014
2A017
2A018
2A019
2A021
2A022
2A024
2A026
2A027
2A028
2A031
2A032
2A035
2A038
2A040
2A041
2A048
2A056
2A060
2A061
2A062
2A064
2A065
2A066
2A070
2A071
2A085
2A089
2A090
2A091
2A092
2A094
2A098
2A099
2A100
2A103
2A104
2A108
2A114
2A115
2A117
2A118
2A119
2A127
2A128
2A129
2A130
2A131
2A132
2A133
2A139
2A141
2A142
2A144
2A146
2A154
2A158
2A160
2A163
2A174
2A181
2A186
2A189
2A191
2A196
2A197
2A198
2A200
2A203
2A204
2A209
2A211
2A212
2A215
2A228
2A232
2A240
2A247
2A249
2A253
2A254
2A258
2A259
2A262
2A266
2A268
2A269
2A270
2A271
2A272
2A276
2A278
2A279
2A282
2A284
2A285
2A288
2A295
2A300
2A308
2A310
2A312
2A322
2A323
2A324
2A326
2A330
2A331
2A336
2A345
2A348
2A349
2A351
2A357
2A358
2A359
2A360
2A362
2A363
2B002
2B003
2B005
2B007
2B009
2B010
2B012
2B013
2B015
2B016
2B020
2B023
2B025
2B029
2B030
2B033
2B034
2B036
2B037
2B039
2B042
2B043
2B045
2B046
2B047
2B049
2B050
2B051
2B052
2B053
2B054
2B055
2B057
2B058
2B059
2B063
2B067
2B068
2B069
2B072
2B073
2B074
2B075
2B077
2B078
2B079
2B080
2B081
2B082
2B083
2B084
2B086
2B087
2B088
2B093
2B095
2B096
2B097
2B101
2B102
2B105
2B106
2B107
2B109
2B110
2B111
2B112
2B113
2B116
2B120
2B121
2B122
2B123
2B124
2B125
2B126
2B134
2B135
2B136
2B137
2B138
2B140
2B143
2B145
2B147
2B148
2B149
2B150
2B152
2B153
2B155
2B156
2B157
2B159
2B161
2B162
2B164
2B165
2B166
2B167
2B168
2B169
2B170
2B171
2B172
2B173
2B175
2B176
2B177
2B178
2B179
2B180
2B182
2B183
2B184
2B185
2B187
2B188
2B190
2B192
2B193
2B194
2B195
2B199
2B201
2B202
2B205
2B206
2B207
2B208
2B210
2B213
2B214
2B216
2B217
2B218
2B219
2B220
2B221
2B222
2B223
2B224
2B225
2B226
2B227
2B229
2B230
2B231
2B233
2B234
2B235
2B236
2B238
2B239
2B241
2B242
2B243
2B244
2B245
2B246
2B248
2B250
2B251
2B252
2B255
2B256
2B257
2B260
2B261
2B263
2B264
2B265
2B267
2B273
2B274
2B275
2B277
2B280
2B281
2B283
2B286
2B287
2B289
2B290
2B291
2B292
2B293
2B296
2B297
2B298
2B299
2B301
2B302
2B303
2B304
2B305
2B306
2B307
2B309
2B311
2B313
2B314
2B315
2B316
2B317
2B318
2B319
2B320
2B321
2B327
2B328
2B329
2B332
2B333
2B334
2B335
2B337
2B338
2B339
2B340
2B341
2B342
2B343
2B344
2B346
2B347
2B350
2B352
2B353
2B354
2B355
2B356
2B361
2B364
2B365
2B366

In [ ]:
odis_emploi_demandeur.sort_values("YEAR")

       codgeo            YEAR  Demandeurs_Emploi
32636   30047       aout_2020                550
79850   57433       aout_2020               1180
27881   28103       aout_2020                410
55853   40184       aout_2020                860
79774   57336       aout_2020                660
...       ...             ...                ...
136678  83099  septembre_2025               1270
5191    06079  septembre_2025               2700
45489   34300  septembre_2025                700
45586   34327  septembre_2025                840
46084   35024  septembre_2025               1110

[170116 rows x 3 columns]

In [ ]:
no_numericos = odis_emploi_demandeur.loc[
    pd.to_numeric(odis_emploi_demandeur["codgeo"], errors="coerce").isna()
    & odis_emploi_demandeur["codgeo"].notna(),
    ["codgeo"],
]
for v in no_numericos["codgeo"]:
    print(v)

2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A004
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2A247
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B033
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B037
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B042
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B050
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B096
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B120
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
2B148
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg01
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg02
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg03
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg04
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg11
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg24
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg27
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg28
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg32
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg44
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg52
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg53
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg75
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg76
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg84
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94
reg94

In [ ]:
from datetime import datetime

cat_nat_df.head(10)
climate_data = pd.DataFrame(
    {
        "lib_commune": cat_nat_df["lib_commune"],
        "cod_commune": cat_nat_df["cod_commune"],
        "climate_risk": cat_nat_df["lib_risque_jo"],
        "durée événement": pd.to_datetime(cat_nat_df["dat_fin"], format="mixed")
        - pd.to_datetime(cat_nat_df["dat_deb"], format="mixed"),
        "cat_nat_recognition": cat_nat_df["dat_pub_jo"],
        "recognition_time": pd.to_datetime(cat_nat_df["dat_pub_jo"], format="mixed")
        - pd.to_datetime(cat_nat_df["dat_fin"], format="mixed"),
    }
)


df_demandeur = (
    odis_emploi_demandeur.groupby("codgeo")
    .agg(nb_demandeurs=("Demandeurs_Emploi", "mean"))
    .reset_index()
)

df_eco = pd.merge(
    df_demandeur, odis_topology, left_on="codgeo", right_on="codgeo"
).reset_index(drop=True)
df_eco["taux_demandeur_emploi"] = (
    df_demandeur["demandeur"] / odis_topology["population"]
)

In [21]:
df_demandeur

     codgeo  nb_demandeurs
0     00001   52017.605634
1     00002   59202.957746
2     00003   30838.028169
3     00004   18130.000000
4     00005   15217.887324
...     ...            ...
2391  reg53  295741.267606
2392  reg75  565267.042254
2393  reg76  658880.281690
2394  reg84  718893.098592
2395  reg94   24863.239437

[2396 rows x 2 columns]